name: CD - Build zip archieve
on:
  push:
    tags:
      - "*"
jobs:
  create-archieve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: extract_tag
        run: echo "GH_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: montudor/action-zip@v1.0.0
        with:
          args: zip -qq -r google-cloud-dark-theme-$GH_TAG.zip *.js manifest.json *.html ./assets/*
      - uses: actions/upload-artifact@v4
        with:
          name: google-cloud-dark-theme-${{ github.ref_name }}.zip
          path: ${{ github.workspace }}/
